# docker-compose.yml
version: "3"
services:
  oneindex-limit-docker:
    container_name: oneindex-limit-docker
    image: quericy/oneindex-limit
    restart: always
    environment:
    - REFRESH_TOKEN=0/60 * * * *
    - REFRESH_CACHE=*/30 * * * *
    volumes:
    - ./config:/var/www/html/config
    - ./cache:/var/www/html/cache