# docker-compose.yml
version: "3"
services:
  oneindex:
    image: quericy/oneindex-limit
    environment:
    - REFRESH_TOKEN=0/120 * * * *
    - REFRESH_CACHE=*/30 * * * *
    # - DISABLE_CRON=true
    # - SSH_PASSWORD=root
    # - TZ=Asia/Shanghai
    volumes:
    - ./config:/var/www/html/config
    - ./cache:/var/www/html/cache
